spring.application.name=demo
server.port=8081
spring.cloud.aws.credentials.access-key=${AWS_ACCESS_KEY_ID:localstack}
spring.cloud.aws.credentials.secret-key=${AWS_SECRET_ACCESS_KEY:localstack}
spring.cloud.aws.region.static=${AWS_REGION:us-east-1}

queue.order-events=${QUEUE_ORDER_EVENTS:T03N_EDSOM_GABRIEL_POMMER_DLQ.fifo}

spring.datasource.url=jdbc:h2:file:./data/auditoria_dlq;
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
